[CI] Add job for running actual programs instead of assembly tests

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -123,3 +123,70 @@ jobs:
           name: vcd-trace-files
           path: |
             test/${{ matrix.unit }}/*.vcd
+
+  demo:
+    needs: verilator
+    runs-on: ubuntu-22.04
+    strategy:
+      fail-fast: false
+      matrix:
+        prog: [test, foo]
+        main_core: [ibex, cv32e40x]
+        cfg:
+          - "VPROC_CONFIG=compact VREG_W=128  VMEM_W=32"
+          - "VPROC_CONFIG=dual    VREG_W=128  VMEM_W=32"
+          - "VPROC_CONFIG=dual    VREG_W=512  VMEM_W=256  ICACHE_SZ=8192 DCACHE_SZ=65536 MEM_LATENCY=5"
+          - "VPROC_CONFIG=triple  VREG_W=256  VMEM_W=32"
+          - "VPROC_CONFIG=triple  VREG_W=1024 VMEM_W=256  ICACHE_SZ=8192 DCACHE_SZ=65536 MEM_LATENCY=5"
+          - "VPROC_CONFIG=legacy  VREG_W=128  VMEM_W=32"
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+
+      - uses: actions/cache@v2
+        id: cache-verilator
+        with:
+          path: /opt/verilator
+          key: ubuntu-22_04-verilator-4_210
+
+      - name: Abort if no cache
+        if: steps.cache-verilator.outputs.cache-hit != 'true'
+        run: exit 1
+
+      - name: Install packages
+        run: |
+          sudo apt-get update
+          sudo apt-get install git perl python3 g++ ccache libfl2 libfl-dev zlib1g zlib1g-dev
+          sudo apt-get install srecord llvm-14 clang-14
+          sudo ln -sf /usr/bin/llvm-objdump-14 /usr/bin/llvm-objdump
+          sudo ln -sf /usr/bin/llvm-objcopy-14 /usr/bin/llvm-objcopy
+
+      - name: Run tests
+        shell: bash {0} # disable fail-fast behavior
+        run: |
+          export PATH=$PATH:/opt/verilator/bin:/opt/riscv-gcc/bin
+          verilator --version
+          retval=0
+          while IFS= read -ra line; do
+            if [ -z "$line" ] || [ "${line:0:1}" = "#" ]; then
+              continue
+            fi
+            echo "$line" > test/${{ matrix.unit }}/test_configs.conf
+            # vcd=`echo "${{ matrix.unit }}_${{ matrix.main_core }}_${line}.vcd" | sed 's/  */_/g'`
+            make -C docs/code PROG=${{ matrix.prog }} OBJ=${{ matrix.prog }}.o CORE=${{ matrix.main_core }} FULL_LOG=1 # TRACE_VCD=$vcd
+            echo "$(pwd)/docs/code/${{ matrix.prog }}.vmem" > sim/progs.txt
+            timeout 360 make -C sim CORE=${{ matrix.main_core }} ${{ matrix.cfg }}
+            if [ $? -ne 0 ]; then
+              retval=1
+            fi
+          done < .github/test_configs.conf
+          exit $retval
+
+      # - name: Archive VCD trace files
+      #   if: failure()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: vcd-trace-files
+      #     path: |
+      #       test/${{ matrix.unit }}/*.vcd
