Store simulation trace files as CI artifacts
Generate VCD trace files when simulating the tests in Verilator within
the CI workflow.  Store these trace files as artifacts.

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -98,8 +98,28 @@ jobs:
           sudo ln -sf /usr/bin/llvm-objcopy-14 /usr/bin/llvm-objcopy
 
       - name: Run tests
+        shell: bash {0} # disable fail-fast behavior
         run: |
           export PATH=$PATH:/opt/verilator/bin:/opt/riscv-gcc/bin
           verilator --version
-          cp .github/test_configs.conf test/${{ matrix.unit }}/
-          cd test && make ${{ matrix.unit }} CORE=${{ matrix.main_core }}
+          retval=0
+          while IFS= read -ra line; do
+            if [ -z "$line" ] || [ "${line:0:1}" = "#" ]; then
+              continue
+            fi
+            echo "$line" > test/${{ matrix.unit }}/test_configs.conf
+            vcd=`echo "trace_${line}.vcd" | sed 's/  */_/g ; s/=/-/g'`
+            make -C test ${{ matrix.unit }} CORE=${{ matrix.main_core }} TRACE_VCD=$vcd
+            if [ $? -ne 0 ]; then
+              retval=1
+            fi
+          done < .github/test_configs.conf
+          exit $retval
+
+      - name: Archive VCD trace files
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: vcd-trace-files
+          path: |
+            test/${{ matrix.unit }}/trace_*.vcd
